In [15]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([1,2,3,4])
print(arr.dtype)
arr.shape

int32


(4,)

# Addition

In [8]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[4,3,7],[2,7,9],[8,9,3]])
out = np.add(arr1,arr2)
print(out)
print(out.shape)

[[ 5  5 10]
 [ 6 12 15]
 [15 17 12]]
(3, 3)


# Transpose

In [9]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
out = arr4.transpose()
print(out)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Mul

In [10]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[4,3,7],[2,7,9],[8,9,3]])
out = arr1.dot(arr2)
print(out)

[[ 32  44  34]
 [ 74 101  91]
 [116 158 148]]


In [12]:
x= np.arange(9).reshape(3,3)
print(x)
print("coloumns ")
print(x[:,0])
print(x[:,1])
print(x[:,2])
print("Rows ")
print(x[0,:])
print(x[1,:])
print(x[2,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
coloumns 
[0 3 6]
[1 4 7]
[2 5 8]
Rows 
[0 1 2]
[3 4 5]
[6 7 8]


In [16]:
df= pd.read_csv(r"C:\Users\hp\Downloads\data.csv")
s = np.array(df)
s

array([['France', 44.0, 72000.0, 'No', 1],
       ['Spain', 27.0, 48000.0, 'Yes', 1],
       ['Germany', 30.0, 54000.0, 'Yes', 2],
       ['Spain', nan, 61000.0, 'No', 3],
       ['Germany', 40.0, nan, 'Yes', 1],
       ['France', 35.0, 58000.0, 'Yes', 2]], dtype=object)